[project]
name = "agent87-github-io"
version = "0.1.0"
description = "Personal blog"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material>=9.5.49",
    "mkdocs>=1.6.1",
]
